import styles from '../../../CatalogLayout.module.scss';
import { Header } from '@/widgets/Header/Header';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dobre | Catalog',
  description: 'Generated by create next app',
};
export default function ProductPageLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <main>
        <div className={styles.catalogWrapper}>{children}</div>
      </main>
    </>
  );
}
