import { Metadata } from 'next';

import styles from './CatalogLayout.module.scss';

import { Footer } from '@/widgets/Footer/Footer';
import { Header } from '@/widgets/Header/Header';

export const metadata: Metadata = {
  title: 'Dobre | Catalog',
  description: 'Generated by create next app',
};
export default function CatalogLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <main>
        <div className={styles.catalogWrapper}>{children}</div>
      </main>
      <Footer />
    </>
  );
}
