import styles from '../CatalogLayout.module.scss';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dobre | Catalog',
  description: 'Generated by create next app',
};
export default function CatalogLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <main>
        <div className={styles.catalogWrapper}>{children}</div>
      </main>
      <Footer />
    </>
  );
}
